version: '3'
services:
  web:
    image: busyreadingsomething/menus
    ports:
      - "4000:3005"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis