const adjectives = [
  'homespun',
  'organic',
  'free-range',
  'winter',
  'late-summer',
  'fermented',
  'invigorated',
  'homemade',
  'cruelty-free',
  'aerated',
  'expanded',
  'distressed',
  'rubbed',
  'activated',
  'pan-seared',
  'stubbed',
  'palmed',
  'miniature',
  'natural',
  'frightened',
  'bludgeoned',
  'charcoal-rubbed',
  'farm-to-table',
  'sheltered',
  'lifted',
  'rounded',
  'beer-braised',
  'country',
  'rustic',
  'massaged',
  'burnt',
  'pressed',
  'japanese',
  'expanded',
  'french',
  'seasonal',
  'blistered',
  'quickened',
  'crafted',
  'artisinal',
  'turned',
  'naive',
];

const nouns = [
  'seaweed',
  'artichoke',
  'anchovy',
  'fennel',
  'millet',
  'acorn',
  'watermelon',
  'monkfish',
  'pork-saddle',
  'mountain oysters',
  'sunflower',
  'pork belly',
  'lamb',
  'sardines',
  'kale',
  'fig',
  'toast',
  'ham',
  'marrow',
  'watercress',
  'chorizo',
  'water',
  'eggplant',
  'bluefish',
  'blood sausage',
  'rice',
  'brussel sprouts',
  'broccolini',
  'asparagus',
  'scallops',
  'cremini mushrooms',
  'bacon',
  'prosciutto',
  'avocado',
  'avocado on toast',
];

const types = [
  'jam',
  'mousse',
  'puree',
  'spread',
  'toss',
  'souffle',
  'platter',
  'booze',
  'pate',
  'discs',
  'crust',
  'crumble',
  'pepper',
  'jus',
  'drippings',
  'confit',
];

const joiner = [
  '&',
  'with',
  'coated in',
  'wrapped in',
  'drizzled in',
  'on a bed of',
];

const desserts = [
  'deconstructed cornbread puree',
  'late-summer berry creme brulee',
  'damson plum clafoutis',
  'roaster pears with espresso mascarpone cream',
  'poppyseed cake with passion-fruit curd',
  'cannoli',
  'strawberry mint souffle',
  'deconstructed lave cake',
  'frozen cookie dough',
  'salted caramel bundt cake',
  'lemon paste curd tart',
  'blackout cake',
  'flourless vanilla chocolate brownie',
  'bear claw',
  'bedfordshire clanger',
  'cherry pie & burnt ginger flakes',
  'brandy snaps',
  'girl guide cookies',
  'black mango and blood orange truffles',
];

module.exports = {
  adjectives,
  nouns,
  types,
  joiner,
  desserts,
};
